version: '3.1'

services:
  mongo-service:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret

  backend-service:
    container_name: backend-mern
    # image: localhost/backend-mern:latest
    build:
      context: ./back-end
    ports:
      - 5002:5002

  frontend-service:
    container_name: frontend-mern
    build:
      context: ./front-end
    # image: localhost/frontend-mern:latest
    ports:
      - 7002:7002

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: "admin"
      ME_CONFIG_BASICAUTH_PASSWORD: "admin"
      ME_CONFIG_MONGODB_URL: mongodb://admin:secret@mongodb:27017/
